# Mongo config
spring:
  data:
    mongodb:
      database: customersquery
      host: ${MONGO_HOST:localhost}
      port: 27017
  application:
    name: customers-query
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

# Service Discovery Config
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaserver:8761/eureka}
  instance:
    preferIpAddress: true

amqp:
  events:
    host: ${RABBIT_HOST:localhost}
    exchange-name: eventBus-customer
    queue-name: eventQueue-customer
    handlers: com.ultimatesoftware.banking.customer.query.domain.eventhandlers

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false
