# Mongo config
spring:
  data:
    mongodb:
      database: yourdb
      host: localhost
      port: 27017
      username:
      password:
  application:
    name: customers
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

server:
  port: 8081

# Service Discovery Config
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true

axon:
  events-base-package: ultimatesoftware.banking.customers.domain.events
  command-handlers-base-package: ultimatesoftware.banking.customers.domain.aggregates
  event-handlers-base-package: ultimatesoftware.banking.customers.domain.eventhandlers
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: ${mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/customers-cmd
          aggregates:
            - CustomerAggregate
amqp:
    commands:
      exchange-name: cmdBus
    events:
      exchange-name: eventBus
      queue-name: eventQueue

