micronaut:
    application:
        name: customer
    router:
        static-resources:
            swagger:
                enabled: true
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
    server:
        port: "${HOST_PORT:8083}"

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"