micronaut:
    application:
        name: account-cmd
    router:
        static-resources:
            swagger:
                enabled: true
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
    server:
        port: "${HOST_PORT:8082}"
    http:
        services:
            people-gateway:
                urls:
                    - "http://${PEOPLE_GATEWAY:localhost}:${PEOPLE_GATEWAY_PORT:8081}"
axon:
    axonserver:
        servers: ${AXON_HOST:localhost}
        component-name: account-cmd

consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"


