spring:
  application:
    name: accountquery
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 27017

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    preferIpAddress: true

axon:
  axonserver:
    servers: localhost
    component-name: accountquery

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false
