language: java
jdk:
- oraclejdk8
sudo: required
script:
  - export MICRONAUT_ENVIRONMENTS=external_mocks
  - ./gradlew build -x test
  - ./gradlew test --tests "*.unit.*"
  - ./gradlew test --tests "*.isolation.*"
after_success: ./gradlew jacocoTestReport coveralls