version: '3'
services:
  customers:
    image: aista/banking-customers
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  accountcmd:
    build: aista/banking-account-cmd
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - MONGO_HOST=mongo
      - RABBIT_HOST=rabbitmq

  accountquery1:
    build: aista/banking-account-query
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - MONGO_HOST=mongo
      - RABBIT_HOST=rabbitmq
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  transactionserver:
    build: aista/banking-transactions
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
    restart: on-failure

volumes:
  mongo:
