version: '2'
services:
  discoveryservice:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    networks:
      - bank
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
    networks:
      - bank
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bank
  configurationservice:
    image: aista/configuration-service
    ports:
      - '8888:8080'
    depends_on:
      - discoveryservice
    networks:
      - bank

networks:
  bank:
    driver: bridge

volumes:
  mongo:
