version: '2.1'
services:
  customerquery:
    build: customer-query/
    depends_on:
      - mongo
      - rabbitmq
    mem_limit: 700m
    ports:
      - "8082:8080"
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"

  customercmd:
    build: customer-cmd/
    depends_on:
      - mongo
      - rabbitmq
    mem_limit: 700m
    ports:
      - "8079:8080"
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"

  accountcmd:
    build: account-cmd/
    depends_on:
      - mongo
      - rabbitmq
    mem_limit: 700m
    ports:
      - "8083:8080"
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo

  accountquery:
    build: account-query/
    depends_on:
      - mongo
      - rabbitmq
    mem_limit: 700m
    ports:
      - "8084:8080"
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"

  transactionserver:
    build: transactions/
    depends_on:
      - mongo
    mem_limit: 700m
    ports:
      - "8085:8080"
    environment:
      - MONGO_HOST=mongo
    restart: on-failure

      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"

  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  eurekaserver:
    image: springcloud/eureka
    ports:
      - "8761:8761"
#  configurationservice:
#    image: aista/configuration-service
#    ports:
#      - "8888:8080"


volumes:
  mongo:
