version: '2.1'
services:
  customers:
    image: rodolpheche/wiremock
    ports:
      - "8085:8080"
    volumes:
      - ./wiremock/customers:/home/wiremock
    restart: on-failure

  accountcmd:
    image: rodolpheche/wiremock
    ports:
      - "8082:8080"
    volumes:
      - ./wiremock/accountcmd:/home/wiremock
    restart: on-failure

  accountquery:
    image: rodolpheche/wiremock
    ports:
      - "8084:8080"
    volumes:
      - ./wiremock/accountquery:/home/wiremock
    restart: on-failure

#  transactionserver:
#    build: transactions/
#    mem_limit: 400m
#    ports:
#      - "8086:8086"
#    environment:
#      - CONSUL_HOST=discovery-service
#      - HOST_PORT=8086
#      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
#    restart: on-failure

  discovery-service:
    image: bitnami/consul:latest
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'

  axonserver:
    image: 'axoniq/axonserver'
    ports:
      - '8124:8124'
      - '8024:8024'

  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/mongo/db'
volumes:
  mongo:
