version: '3'
services:
  eureka-server:
    image: springcloud/eureka
    ports:
      - "8761:8761"

  customer-server:
    build: customers/
    depends_on:
      - eureka-server
      - mongo
    ports:
      - "8081:8081"

  account-server:
    build: accounts/
    depends_on:
      - eureka-server
      - mongo
    ports:
      - "8084:8084"

  transaction-server:
    build: transactions/
    depends_on:
      - eureka-server
      - mongo
    ports:
      - "8085:8085"
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
volumes:
  mongo:
