version: '2'
services:
  customerquery:
    build: customer-query/
    ports:
      - "8082:8080"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
  customercmd:
    build: customer-cmd/
    ports:
      - "8079:8080"
    networks:
      - banking-microservices-example_bank
    restart: on-failure

  accountcmd:
    build: account-cmd/
    ports:
      - "8083:8080"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
  accountquery:
    build: account-query/
    ports:
      - "8084:8080"
    networks:
      - banking-microservices-example_bank
    restart: on-failure

  transactionserver:
    build: transactions/
    ports:
      - "8085:8080"
    environment:
      - MONGO_HOST=mongo
    networks:
      - banking-microservices-example_bank
    restart: on-failure

networks:
  banking-microservices-example_bank:
    external: true

volumes:
  mongo:
