version: '3'
services:
  discoveryservice:
    image: 'aista/eureka'
    ports:
      - "8761:8761"
  edgeservice:
    image: 'aista/banking-edgeservice'
    ports:
      - "8080:8080"
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  configurationservice:
    image: aista/configuration-service
    ports:
      - '8080:8080'
    depends_on:
      - discoveryservice

volumes:
  mongo:
