version: '3'
services:
  discovery-service:
    image: bitnami/consul:latest
    networks:
      - bank
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'

  people-gateway:
    build: docker/express-gateway/
    ports:
      - "8081:8080"
      - "8443:8443"
      - "9876:9876"
    volumes:
      - ./docker/express-gateway/people-configuration/system.config.yml:/usr/src/app/config/system.config.yml
      - ./docker/express-gateway/people-configuration/gateway.config.yml:/usr/src/app/config/gateway.config.yml
    networks:
      - bank
    depends_on:
      - redis

  account-gateway:
    build: docker/express-gateway/
    ports:
      - "8080:8080"
      - "8444:8443"
      - "9877:9876"
    volumes:
      - ./docker/express-gateway/account-configuration/system.config.yml:/usr/src/app/config/system.config.yml
      - ./docker/express-gateway/account-configuration/gateway.config.yml:/usr/src/app/config/gateway.config.yml
    depends_on:
      - redis

  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/mongo/db'
    networks:
      - bank

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data/redis'
    networks:
      - bank

  axonserver:
    image: 'axoniq/axonserver'
    ports:
      - '8124:8124'
      - '8024:8024'
    networks:
      - bank

networks:
  bank:
    driver: bridge

volumes:
  redis:
  mongo:
