version: '3'
services:
  eureka-server:
    image: springcloud/eureka
    ports:
      - "8761:8761"

  customer-query:
    build: customers-query/
    depends_on:
      - eureka-server
      - mongo
    ports:
      - "8082:8082"

  customer-cmd:
      build: customers-cmd/
      depends_on:
        - eureka-server
        - mongo
      ports:
        - "8081:8081"

  account-server:
    build: accounts/
    depends_on:
      - eureka-server
      - mongo
    ports:
      - "8084:8084"

  transaction-server:
    build: transactions/
    depends_on:
      - eureka-server
      - mongo
    ports:
      - "8085:8085"
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  mongo:
