version: '2.1'
services:
  people-details:
    build: people-details/
    mem_limit: 400m
    ports:
      - "8085:8085"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - HOST_PORT=8085
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  people-cmd:
    build: people-cmd/
    mem_limit: 400m
    ports:
      - "8087:8087"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - HOST_PORT=8087
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  people-authentication:
    build: people-authentication/
    mem_limit: 400m
    ports:
      - "8088:8088"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - HOST_PORT=8088
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  account-cmd:
    build: account-cmd/
    mem_limit: 400m
    ports:
      - "8082:8082"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - AXON_HOST=axonserver
      - HOST_PORT=8082

  account-query:
    build: account-query/
    mem_limit: 400m
    ports:
      - "8084:8084"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - AXON_HOST=axonserver
      - HOST_PORT=8084
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  account-transaction:
    build: account-transactions/
    mem_limit: 400m
    ports:
      - "8086:8086"
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - AXON_HOST=axonserver
      - HOST_PORT=8086
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
    networks:
      - banking-microservices-example_bank
    restart: on-failure

networks:
  banking-microservices-example_bank:
    external: true

volumes:
  mongo:
