version: '2.1'
services:
  discovery-service:
    image: bitnami/consul:latest
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'

  people-gateway:
    build: docker/express-gateway/
    ports:
      - "8081:8080"
      - "8443:8443"
      - "9876:9876"
    volumes:
      - ./docker/express-gateway/people-configuration/system.config.yml:/usr/src/app/config/system.config.yml
      - ./docker/express-gateway/people-configuration/gateway.config.yml:/usr/src/app/config/gateway.config.yml
    depends_on:
      - redis

  account-gateway:
    build: docker/express-gateway/
    ports:
      - "8080:8080"
      - "8444:8443"
      - "9877:9876"
    volumes:
      - ./docker/express-gateway/account-configuration/system.config.yml:/usr/src/app/config/system.config.yml
      - ./docker/express-gateway/account-configuration/gateway.config.yml:/usr/src/app/config/gateway.config.yml
    depends_on:
      - redis

  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/mongo/db'

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data/redis'

  axonserver:
    image: 'axoniq/axonserver'
    ports:
      - '8124:8124'
      - '8024:8024'

  people-details:
    build: domain-services/people-details/
    mem_limit: 400m
    ports:
      - "8085:8085"
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - HOST_PORT=8085
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  people-cmd:
    build: domain-services/people-cmd/
    mem_limit: 400m
    ports:
      - "8087:8087"
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - HOST_PORT=8087
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  people-authentication:
    build: domain-services/people-authentication/
    mem_limit: 400m
    ports:
      - "8088:8088"
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - HOST_PORT=8088
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  account-cmd:
    build: domain-services/account-cmd/
    mem_limit: 400m
    ports:
      - "8082:8082"
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - AXON_HOST=axonserver
      - HOST_PORT=8082

  account-query:
    build: domain-services/account-query/
    mem_limit: 400m
    ports:
      - "8084:8084"
    restart: on-failure
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - AXON_HOST=axonserver
      - HOST_PORT=8084
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  account-transaction:
    build: domain-services/account-transactions/
    mem_limit: 400m
    ports:
      - "8086:8086"
    environment:
      - CONSUL_HOST=discovery-service
      - MONGO_HOST=mongo
      - AXON_HOST=axonserver
      - HOST_PORT=8086
      - PEOPLE_DETAILS_HOST=
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
    restart: on-failure

volumes:
  redis:
  mongo:
