version: '2.1'
services:
  customers:
    build: customers/
    ports:
      - "8085:8085"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
    environment:
      - MONGO_HOST=mongo
      - HOST_PORT=8085
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  accountcmd:
    build: account-cmd/
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
    environment:
      - MONGO_HOST=mongo

  accountquery:
    build: account-query/
    mem_limit: 800m
    ports:
      - "8084:8084"
    networks:
      - banking-microservices-example_bank
    restart: on-failure
    environment:
      - MONGO_HOST=mongo
      - HOST_PORT=8084
      - ES_JAVA_OPTS= "-Xms450mb -Xmx450mb"

  transactionserver:
    build: transactions/
    mem_limit: 800m
    ports:
      - "8086:8086"
    environment:
      - MONGO_HOST=mongo
      - HOST_PORT=8086
      - ES_JAVA_OPTS= "-Xms150mb -Xmx150mb"
    networks:
      - banking-microservices-example_bank
    restart: on-failure

networks:
  banking-microservices-example_bank:
    external: true

volumes:
  mongo:
