version: '2'
services:
  discoveryservice:
    image: 'aista/eureka'
    ports:
      - "8761:8761"
    networks:
      - bank
  edgeservice:
    build: 'edgeservice/'
    ports:
      - "8080:8080"
    networks:
      - bank
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
    networks:
      - bank
  axonserver:
    image: 'axoniq/axonserver'
    ports:
      - '8124:8124'
      - '8024:8024'
    networks:
      - bank

networks:
  bank:
    driver: bridge

volumes:
  mongo:
