#spring.profiles.active: test
spring:
  profiles: test
  application:
    name: accountcmd

axon:
  axonserver:
    servers: axonserver

server:
  port: 8080

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false

