micronaut:
    application:
        name: account-transactions
    router:
        static-resources:
            swagger:
                enabled: true
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
    server:
        port: "${HOST_PORT:8086}"
    http:
        services:
            people-gateway:
                urls:
                    - "http://${PEOPLE_GATEWAY:localhost}:${PEOPLE_GATEWAY_PORT:8081}"

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

ribbon:
    VipAddress: test
    ServerListRefreshInterval: 2000

axon:
    axonserver:
        servers: ${AXON_HOST:localhost}
        component-name: account-transactions

consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"


endpoints:
    health:
        enabled: true
        sensitive: false
    metrics:
        enabled: true
        sensitive: false
