#spring.profiles.active: test
spring:
  profiles: test
  application:
    name: accountquery
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 27017

server:
  port: 8080

axon:
  axonserver:
    servers: axonserver

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false

