micronaut:
    application:
        name: account.command
    router:
        static-resources:
            swagger:
                enabled: true
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

axon:
    axonserver:
        servers: localhost
        component-name: accountcommand