http:
  port: 8080
admin:
  port: 9876
  hostname: 0.0.0.0
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  api:
    host: '*'
    paths: '/ip'
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  people-details:
    url: 'https://localhost:8085'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  basic:
    apiEndpoints:
      api:
        host: 'localhost'
        paths: '/api/v1/people'
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: people-details
              changeOrigin: true