# Mongo config
spring:
  data:
    mongodb:
      database: accountcmd
      host: localhost
      port: 27017
      username:
      password:
  application:
    name: account-cmd

server:
  port: 8083

# Service Discovery Config
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true

axon:
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: ${mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/accountcmd

amqp:
    events:
      host: localhost
      exchange-name: eventBus-account
      queue-name: eventQueue-account
      handlers:
