# Mongo config
spring:
  data:
    mongodb:
      database: accountcmd
      host: ${MONGO_HOST:localhost}
      port: 27017
  application:
    name: accountcmd
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

server:
  port: 8080

# Service Discovery Config
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaserver:8761/eureka}
  instance:
    preferIpAddress: true

axon:
  cluster-name: ${spring.application.name}
  eventstore:
    mongo:
      connections:
        default:
          uri: ${mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/accountcmd
          aggregates:
            - Account
amqp:
  events:
    host: ${RABBIT_HOST:localhost}
    exchange-name: eventBus-account
    queue-name: eventQueue-account
    handlers:
