spring:
  application:
    name: transactions
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 27017

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

server:
  port: 8081

axon:
  axonserver:
    servers: localhost
    component-name: transactions

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: health,info
    shutdown:
      enabled: true

hosts:
  account-cmd: localhost:8089
  account-query: localhost:8084
  customers: localhost:8081
