spring:
  application:
    name: transactions
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    auto-config:
      default-exchange:
        type: fanout
        dead-letter-enabled: true
      dead-letter-config:
        dead-letter-exchange:
          name: dead-letter-${spring.application.name}
          auto-delete: true
          durable: false
        queue-postfix: .dlq
      queues:
        eventQueue-account:
          name: eventQueue-account
          dead-letter-enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    preferIpAddress: true

server:
  port: 8080

amqp:
  events:
    host: localhost
    exchange-name: eventBus-account
    queue-name: eventQueue-account-transactions
    handlers: com.ultimatesoftware.banking.transactions.domain.eventhandlers

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false

hosts:
  account-cmd: localhost:8083
  account-query: localhost:8084
  customers: localhost:8081
