spring:
  application:
    name: edgeservice
zuul:
  prefix: /api
  routes:
    account-cmd:
      path: /cmd/accounts/**
      url: http://localhost:8080/api/v1
    account-query:
      path: /query/accounts/**
      url: http://localhost:8080/api/v1
    transactions:
      path: /transactions/**
      url: http://localhost:8080/
    customers:
      path: /customers/**
      url: http://localhost:8080/
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000