#spring.profiles.active: test

spring:
  profiles:
    include: default
  application:
    name: accountcmd

axon:
  axonserver:
    servers: localhost

server:
  port: 8080

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false

