spring:
  application:
    name: accountcmd

security:
  enable-csrf: false

axon:
  axonserver:
    servers: localhost
    component-name: accountcmd

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    preferIpAddress: true

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false

thread-pool:
  size: 5
